### ISSUE TITLE
crashing with Modern-Industrialization-1.5.0

### ISSUE THREAD

**Issue by AsheX1** [ExcessiveAmountsOfZombies/ProfessionsIntegration#1]
just like title says
fabric 1.19.2
rolled back to 1.4.2 of MI

granted Modern-Industrialization-1.5.0 just released

**Comment by AsheX1** [comment]
updated to last version of Modern-Industrialization still happing

**Comment by ExcessiveAmountsOfZombies** [comment]
Uploading a fix right now, 1.0.4
